env:
  browser: true
  es6: true
extends: './node_modules/eslint-config-google/index.js'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  esversion: 6
rules: {
  "indent": ["error", 4],
  "max-len": ["error", {"code": 240}],
  "require-jsdoc" : 0
}
