export default {
    EMITTER_TEST: 'emitter-test',
    UPDATE_NEWS_FEED: 'update-news-feed',
    HIDE_NEWS_FEED: 'hide-news-feed',
    ASSIGNED_DESK: 'assigned-desk',
    STAGE_ONE_COMPLETED: 'stage-one-task-completed',
    STAGE_TWO_COMPLETED: 'stage-two-task-completed',
    PLAY_DOOR_ANIMATION: 'play-door-animation',
    INSPECT_ALGORITHM: 'inspect-algorithm',
    DATASET_VIEW_INSPECT: 'inspect-dataset',
    DATASET_VIEW_NEW_CV: 'dataset-new-cv',
    RESUME_TIMELINE: 'resume-timeline',
    SHOW_TOOLTIP: 'show-tooltip',
    DESTROY_TOOLTIP: 'destroy-tooltip',
    SHOW_ENDGAME_OVERLAY: 'show-endgame-overlay',
    RESIZE: 'resize',
    ACCEPTED: 'accepted',
    REJECTED: 'rejected',
    RETURN_CANDIDATE: 'return-candidate',
    DISPLAY_THIS_CV: 'display-this-cv',
    PERSON_HOVERED: 'person-hovered',
    CHANGE_SPOTLIGHT_STATUS: 'change-spotlight-status',
    MAKE_ML_PEOPLE_TALK: 'show-ml-speech-bubble',
};
